services:
  dremio:
    image: dremio/dremio-oss:${DREMIO_VERSION_TAG}
    container_name: dremio
    hostname: dremio
    platform: linux/x86_64
    ports:
      - 9047:9047
      - 31010:31010
      - 32010:32010
      - 45678:45678
      - 433:433
    environment:
      - DREMIO_JAVA_SERVER_EXTRA_OPTS=-Dpaths.dist=file:///opt/dremio/data/dist
    volumes:
      - ./volumes/dremio/:/opt/dremio/data

    
  minio:
    image: bitnami/minio:${MINIO_VERSION_TAG}
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_DOMAIN: ${MINIO_DOMAIN}
      MINIO_REGION_NAME: ${MINIO_REGION_NAME}
      MINIO_REGION: ${MINIO_REGION}
    volumes:
      - ./volumes/minio/:/bitnami/minio/data

  nessie:
    image: bitnami/nessie:${NESSIE_VERSION_TAG}
    container_name: nessie
    ports:
      - "19120:19120"

  clinical_outcomes_domain:
    container_name: clinical_outcomes_domain
    build: ./clinical_outcomes_domain/
    volumes:
      - ./clinical_outcomes_domain/clinical_outcomes:/usr/src/dbt/clinical_outcomes
      - ./clinical_outcomes_domain/profiles.yml:/root/.dbt/profiles.yml
    environment:
      DBT_PROFILES_DIR: /root/.dbt
    depends_on:
      - minio
      - nessie

  cost_value_domain:
    container_name: cost_value_domain
    build: ./cost_value_domain/
    volumes:
      - ./cost_value_domain/cost_value:/usr/src/dbt/clinical_outcomes
      - ./cost_value_domain/profiles.yml:/root/.dbt/profiles.yml
    environment:
      DBT_PROFILES_DIR: /root/.dbt
    depends_on:
      - minio
      - nessie


networks:
  datamesh: